### ISSUE TITLE
What's the recommended way that this approach can be carried over into production?

### ISSUE THREAD

**Issue by davej** [PolymerLabs/polyserve#14]
Perhaps an nginx config or some other strategy that would work in common production setups.

**Comment by justinfagnani** [comment]
In production this often isn't much of an issue because the top-level app's `bower_components/` folder is addressed as either an absolute URL, or as a relative sub-folder. Once a component within `bower_components/` is loaded, it's `../` relative paths work fine.

Polyserve is only necessary when you have something that is both a component and that you want to directly serve content from, like when working on individual components.

**Comment by ebidel** [comment]
The question was addressed. Closing, as this is pretty old.
